services:
  db:
    image: postgres:15.5-alpine
    restart: always
    container_name: database
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=password
    ports:
      - '5432:5432'
    volumes:
      - $HOME/docker/volumes/sport-management:/var/lib/postgresql/data
volumes:
  db:
    driver: local